cask "ttf-inconsolata" do
  version "3.000"
  sha256 "626e8ee07501dbb544b50aa59ac2e4b9ec86b810670158a59c7a3cbaf475548a"

  url "https://github.com/googlefonts/Inconsolata/releases/download/v#{version}/fonts_ttf.zip",
    verified: "github.com/googlefonts/Inconsolata/"
  name "Inconsolata"
  homepage "https://www.google.com/fonts/specimen/Inconsolata"

  livecheck do
    url "https://github.com/googlefonts/Inconsolata"
    strategy :github_latest
  end

  conflicts_with cask: "font-inconsolata"

  font "fonts/ttf/Inconsolata-Black.ttf"
  font "fonts/ttf/Inconsolata-Bold.ttf"
  font "fonts/ttf/Inconsolata-Condensed.ttf"
  font "fonts/ttf/Inconsolata-CondensedBlack.ttf"
  font "fonts/ttf/Inconsolata-CondensedBold.ttf"
  font "fonts/ttf/Inconsolata-CondensedExtraBold.ttf"
  font "fonts/ttf/Inconsolata-CondensedExtraLight.ttf"
  font "fonts/ttf/Inconsolata-CondensedLight.ttf"
  font "fonts/ttf/Inconsolata-CondensedMedium.ttf"
  font "fonts/ttf/Inconsolata-CondensedSemiBold.ttf"
  font "fonts/ttf/Inconsolata-Expanded.ttf"
  font "fonts/ttf/Inconsolata-ExpandedBlack.ttf"
  font "fonts/ttf/Inconsolata-ExpandedBold.ttf"
  font "fonts/ttf/Inconsolata-ExpandedExtraBold.ttf"
  font "fonts/ttf/Inconsolata-ExpandedExtraLight.ttf"
  font "fonts/ttf/Inconsolata-ExpandedLight.ttf"
  font "fonts/ttf/Inconsolata-ExpandedMedium.ttf"
  font "fonts/ttf/Inconsolata-ExpandedSemiBold.ttf"
  font "fonts/ttf/Inconsolata-ExtraBold.ttf"
  font "fonts/ttf/Inconsolata-ExtraCondensed.ttf"
  font "fonts/ttf/Inconsolata-ExtraCondensedBlack.ttf"
  font "fonts/ttf/Inconsolata-ExtraCondensedBold.ttf"
  font "fonts/ttf/Inconsolata-ExtraCondensedExtraBold.ttf"
  font "fonts/ttf/Inconsolata-ExtraCondensedExtraLight.ttf"
  font "fonts/ttf/Inconsolata-ExtraCondensedLight.ttf"
  font "fonts/ttf/Inconsolata-ExtraCondensedMedium.ttf"
  font "fonts/ttf/Inconsolata-ExtraCondensedSemiBold.ttf"
  font "fonts/ttf/Inconsolata-ExtraExpanded.ttf"
  font "fonts/ttf/Inconsolata-ExtraExpandedBlack.ttf"
  font "fonts/ttf/Inconsolata-ExtraExpandedBold.ttf"
  font "fonts/ttf/Inconsolata-ExtraExpandedExtraBold.ttf"
  font "fonts/ttf/Inconsolata-ExtraExpandedExtraLight.ttf"
  font "fonts/ttf/Inconsolata-ExtraExpandedLight.ttf"
  font "fonts/ttf/Inconsolata-ExtraExpandedMedium.ttf"
  font "fonts/ttf/Inconsolata-ExtraExpandedSemiBold.ttf"
  font "fonts/ttf/Inconsolata-ExtraLight.ttf"
  font "fonts/ttf/Inconsolata-Light.ttf"
  font "fonts/ttf/Inconsolata-Medium.ttf"
  font "fonts/ttf/Inconsolata-Regular.ttf"
  font "fonts/ttf/Inconsolata-SemiBold.ttf"
  font "fonts/ttf/Inconsolata-SemiCondensed.ttf"
  font "fonts/ttf/Inconsolata-SemiCondensedBlack.ttf"
  font "fonts/ttf/Inconsolata-SemiCondensedBold.ttf"
  font "fonts/ttf/Inconsolata-SemiCondensedExtraBold.ttf"
  font "fonts/ttf/Inconsolata-SemiCondensedExtraLight.ttf"
  font "fonts/ttf/Inconsolata-SemiCondensedLight.ttf"
  font "fonts/ttf/Inconsolata-SemiCondensedMedium.ttf"
  font "fonts/ttf/Inconsolata-SemiCondensedSemiBold.ttf"
  font "fonts/ttf/Inconsolata-SemiExpanded.ttf"
  font "fonts/ttf/Inconsolata-SemiExpandedBlack.ttf"
  font "fonts/ttf/Inconsolata-SemiExpandedBold.ttf"
  font "fonts/ttf/Inconsolata-SemiExpandedExtraBold.ttf"
  font "fonts/ttf/Inconsolata-SemiExpandedExtraLight.ttf"
  font "fonts/ttf/Inconsolata-SemiExpandedLight.ttf"
  font "fonts/ttf/Inconsolata-SemiExpandedMedium.ttf"
  font "fonts/ttf/Inconsolata-SemiExpandedSemiBold.ttf"
  font "fonts/ttf/Inconsolata-UltraCondensed.ttf"
  font "fonts/ttf/Inconsolata-UltraCondensedBlack.ttf"
  font "fonts/ttf/Inconsolata-UltraCondensedBold.ttf"
  font "fonts/ttf/Inconsolata-UltraCondensedExtraBold.ttf"
  font "fonts/ttf/Inconsolata-UltraCondensedExtraLight.ttf"
  font "fonts/ttf/Inconsolata-UltraCondensedLight.ttf"
  font "fonts/ttf/Inconsolata-UltraCondensedMedium.ttf"
  font "fonts/ttf/Inconsolata-UltraCondensedSemiBold.ttf"
  font "fonts/ttf/Inconsolata-UltraExpanded.ttf"
  font "fonts/ttf/Inconsolata-UltraExpandedBlack.ttf"
  font "fonts/ttf/Inconsolata-UltraExpandedBold.ttf"
  font "fonts/ttf/Inconsolata-UltraExpandedExtraBold.ttf"
  font "fonts/ttf/Inconsolata-UltraExpandedExtraLight.ttf"
  font "fonts/ttf/Inconsolata-UltraExpandedLight.ttf"
  font "fonts/ttf/Inconsolata-UltraExpandedMedium.ttf"
  font "fonts/ttf/Inconsolata-UltraExpandedSemiBold.ttf"
  font "fonts/ttf/Ligconsolata-Bold.ttf"
  font "fonts/ttf/Ligconsolata-Regular.ttf"

  caveats do
    free_license "https://github.com/googlefonts/Inconsolata/releases/download/v#{version}/OFL.txt"
  end
end
